<a href="https://colab.research.google.com/github/OmotolaAI/Intro.-to-AI-checkpoint./blob/main/Checkpoint(Intro_to_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.

In [8]:
for i in range(2000,3200):
  if i%7==0 and i%5!=0:
    print(i, end=" ")

2002 2009 2016 2023 2037 2044 2051 2058 2072 2079 2086 2093 2107 2114 2121 2128 2142 2149 2156 2163 2177 2184 2191 2198 2212 2219 2226 2233 2247 2254 2261 2268 2282 2289 2296 2303 2317 2324 2331 2338 2352 2359 2366 2373 2387 2394 2401 2408 2422 2429 2436 2443 2457 2464 2471 2478 2492 2499 2506 2513 2527 2534 2541 2548 2562 2569 2576 2583 2597 2604 2611 2618 2632 2639 2646 2653 2667 2674 2681 2688 2702 2709 2716 2723 2737 2744 2751 2758 2772 2779 2786 2793 2807 2814 2821 2828 2842 2849 2856 2863 2877 2884 2891 2898 2912 2919 2926 2933 2947 2954 2961 2968 2982 2989 2996 3003 3017 3024 3031 3038 3052 3059 3066 3073 3087 3094 3101 3108 3122 3129 3136 3143 3157 3164 3171 3178 3192 3199 

2.

In [9]:
def factorial(n):
  if n==1:
    return(n)
  else:
    return n*factorial(n-1)
print(factorial(8))

40320


3.

In [10]:
n=int(input("Enter an mumber:"))
d={x:x*x for x in range(1, n+1)}
print(d)

Enter an mumber:12
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144}


4.

In [11]:
str="waiter"
str=str[:3]+str[4:]
#remove character at index 1
print(str)


waier


5.

In [13]:
import numpy as np
x=np.arange(6).reshape(3,2)
print("Original array elements:")
print(x)
print("Array to list:")
print(x.tolist())

Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


6.

In [14]:
import numpy as numpy
x=np.array([[0,1,2]])
y=np.array([[2,1,0]])
print("\noriginal array1:")
print(x)
print("\noriginal array1:")
print(y)
print("\ncovariance matrix of the said arrays:n",np.cov(x,y))


original array1:
[[0 1 2]]

original array1:
[[2 1 0]]

covariance matrix of the said arrays:n [[ 1. -1.]
 [-1.  1.]]


7.

In [19]:
import math
numbers=input("provide D:")
numbers=numbers.split(",")

result_list=[]
for D in numbers:
  Q=round(math.sqrt(2*50*int(D)/30))
  result_list.append(Q)

  print(result_list)
  

provide D:100,150,180
[18]
[18, 22]
[18, 22, 24]
